language: node_js
node_js:
  - "5"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm i -g npm@latest
install:
  - npm install -g bower
  - npm install
  - bower install
before_script:
  - npm prune
  - npm install -g codecov
script:
  - npm test
after_script:
  - codecov
