language: node_js
node_js:
  - 6.4
sudo: false
addons:
  ssh_known_hosts: mfelten.de
cache:
  directories:
    - node_modules
    - bower_components
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - openssl aes-256-cbc -K $encrypted_a8184e2e8c6b_key -iv $encrypted_a8184e2e8c6b_iv -in config/travis_id_rsa.enc -out config/travis_id_rsa -d
  - chmod 400 config/travis_id_rsa
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt
  - phantomjs --version
install:
  - npm install
  - bower install
before_script:
  - npm install -g codecov
script:
  - npm test
after_script:
  - codecov
after_success:
  - npm run semantic-release
deploy:
  - provider: script
    skip_cleanup: true
    script: ember deploy demo
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ember deploy staging && scp -i config/travis_id_rsa tmp/deploy-archive/kronos-service-manager-ui.tar mfelten_de@mfelten.de:/home/mfelten_de/docroot/kronos/kronos-service-manager-ui.tar
    on:
      branch: master
