language: node_js
node_js:
  - 6.1
sudo: false
addons:
  ssh_known_hosts: mfelten.de
cache:
  directories:
    - node_modules
    - bower_components
    - travis_phantomjs
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - openssl aes-256-cbc -K $encrypted_a8184e2e8c6b_key -iv $encrypted_a8184e2e8c6b_iv -in config/travis_id_rsa.enc -out config/travis_id_rsa -d
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version
  - npm config set spin false
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - npm install -g codecov
script:
  - npm test
after_script:
  - codecov
after_success:
  - npm run semantic-release
deploy:
  - provider: script
    skip_cleanup: true
    script: ember deploy production
    on:
      branch: master
